### ISSUE TITLE
Does THUMT support the latest version of Theano?

### ISSUE THREAD

**Issue by lineryang** [thumt/THUMT#1]
Hi,

Does THUMT support the latest version of Theano?

Thanks,

Tianlin

**Comment by Glaceon31** [comment]
Yes. THUMT also supports Theano 0.9.0 released on 2017/03/20. We notice that there is a small problem with building the optimizer. Fortunately, this error does not affect running THUMT. We are working on solving this problem.

<img width="966" alt="thumt_theano" src="https://user-images.githubusercontent.com/7431362/27778529-244c5dfa-5fee-11e7-9663-60d2d8cd3368.png">
