### ISSUE TITLE
训练对话模型时，会经常出现“”WARNING] There is an NaN!“”这样的提示信息，连续若干次后，训练过程会自动停掉了。

### ISSUE THREAD

**Issue by cyzhangAThit** [thumt/THUMT#11]
训练对话模型时，会经常出现“”WARNING] There is an NaN!“”这样的提示信息，连续若干次后，训练过程会停掉了。出现这个情况的原因是什么？如果避免？

**Comment by Glaceon31** [comment]
这个是训练不收敛的现象，可以尝试调低Adam的学习率试试

**Comment by cyzhangAThit** [comment]
Adam算法如何调整学习率？控制alpha还是beta?
