### ISSUE TITLE
batch size of Minimum risk training

### ISSUE THREAD

**Issue by chenwangliangguo** [thumt/THUMT#12]
Hi, It seems that the batch size of Minimum risk training should be set to 1, this would make the training much slower if the dataset is very large, is there anyway to avoid this?

**Comment by Glaceon31** [comment]
It is not necessary to avoid this. Normally MRT finishes before a single epoch. It is also not practical to avoid this if your GPU memory is not large enough (MRT is quite memory-consuming because of sampling).
