### ISSUE TITLE
训练过程中会出现内存爆炸的问题

### ISSUE THREAD

**Issue by cyzhangAThit** [thumt/THUMT#14]
在data.py中的这个函数
    def format_num(self, x):
        result = str(round(x, 2))
        while result[-3] != '.':
            result += '0'
        return result  
中，如果x不是一个浮点数，比如我遇到的情况，是x是一个inf，那么这个地方就会出现一个死循环，会导致result无限变长，内存会变大，直到被kill

**Comment by Glaceon31** [comment]
谢谢报告，已修复！我们在使用的时候貌似没有遇到过这个情况
