### ISSUE TITLE
embedding_size and hidden_size should be the same?

### ISSUE THREAD

**Issue by monsieurzhang** [thumt/THUMT#16]
Hi,

I try to train a seq2seq model.
It seams I have to set same value for embedding_size and hidden_size.
Otherwise, it will report some errors.

Is that correct?
Thanks.

**Comment by Playinf** [comment]
Yes, this is because the residual function uses add operation, as a result, the dimensions of input and output must match.

**Comment by Playinf** [comment]
Alternatively, you can set `use_residual=false` in additional parameters, which can eliminate this error.
