### ISSUE TITLE
confirmation: only Adam optim is implemented at this time

### ISSUE THREAD

**Issue by monsieurzhang** [thumt/THUMT#17]
based on the code:
https://github.com/thumt/THUMT/blob/81b16687b7ddd0a194a3acc2b5f026768afc6492/thumt/bin/trainer.py#L341

I remember there are others in the older version?

**Comment by Playinf** [comment]
The Theano version of THUMT can use other optimizers. The TensorFlow version only support Adam optimizer. However, you can use other optimizers by change the name of Optimizer (For example, `AdamOptimizer` -> `AdadeltaOptimizer`)
