### ISSUE TITLE
Is the batch size the same for MRT and MLE? 

### ISSUE THREAD

**Issue by dalegebit** [thumt/THUMT#2]
I tried both MRT and MLE without changing the batch size, and I got out of memory error for MRT.
It looks like the model has to process 80 * 100 samples if I set the batch size to 80 and sampleN to 100, strictly following the settings in the original paper of MRT.  However, in my experience, at least 4G intermediate variables have to be stored to compute gradient when training a usable NMT model with batch size 256+. I wonder is it correct to set batch size to 80 for MRT? Or it is only for MLE?

**Comment by miradel51** [comment]
Hi, 


Thanks for asking it. Actually, it was not strictly set for MLE. Generally, We set batch size to 80 both for MRT and MLE. 






Bestwishes,


Miradel







|
MiradelPHD candidate
miradel51@126.com
Lab：Tsinghua NLP & CSS Lab
Room 4-506,FIT building,Tsinghua University,Beijing,China
Computer Science & Technology
Mobile：13051308938
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|

At 2017-08-22 16:49:19, "dalegebit" <notifications@github.com> wrote:


I tried both MRT and MLE without changing the batch size, and I got out of memory error for MRT.
It looks like the model has to process 80 * 100 samples if I set the batch size to 80 and sampleN to 100, strictly following the settings in the original paper of MRT. However, in my experience, at least 4G intermediate variables have to be stored to compute gradient for training a usable NMT model with batch size 256+. I wonder is it correct to set batch size to 80 for MRT? Or it is only for MLE?

**Comment by Glaceon31** [comment]
We only set batch size to 80 for MLE. For MRT, the batch size is set to 1, which is hard-coded in thumt/train.py. Even if you set [mini-batch size] to 80, the batch size is automatically adjust to 1 in MRT training.

However, MRT training require more memory than MLE because it generate samples (100 by default) which may also be longer than the training sentence. If you run out of memory, try to reduce [MRT sample size] and [MRT length ratio limit] in THUMT.config.

**Comment by dalegebit** [comment]
Thank you! By the way, have you ever tried reducing the sample size and increasing the batch size, which means calculating the expectation for not only one sequence?

**Comment by Glaceon31** [comment]
Thanks for the suggestion! Actually we have not tried that yet. We will allow user-defined batch size for MRT if it turns out to be useful.
