### ISSUE TITLE
文档中decoding一节(3.3节)有个笔误

### ISSUE THREAD

**Issue by cyzhangAThit** [thumt/THUMT#20]
1 $ python THUMT/thumt/bin/translator.py --models transformer
2 --input newstest2015.tc.32k.de --output newstest2015.trans
3 --vocabulary vocab.32k.de vocab.32k.en --checkpoints train/eval
4 --parameters=device_list[0]

第4行这里应该为 --parameters=device_list=[0]

**Comment by Playinf** [comment]
Thank you for reporting. You may compile UserManual.tex for the latest version of Manual.
