### ISSUE TITLE
The error of trainer

### ISSUE THREAD

**Issue by KelleyYin** [thumt/THUMT#23]
There is my command as follow . What cause the error and how to solve it ?
`mmyin@amax:/data2/mmyin/experiment$ python THUMT/thumt/bin/trainer.py --input ch.txt.32k.shuf en.txt.32k.shuf --vocabulary vocab.32k.ch.txt vocab.32k.en.txt --model rnnsearch --validation ch.volid.32k --references en.volid.32k --parameters=batch_size=128,device_lise=[2],train_steps=200000
Traceback (most recent call last):
  File "THUMT/thumt/bin/trainer.py", line 15, in <module>
    import thumt.data.cache as cache
ImportError: No module named thumt.data.cache
`
Thanks in advance .

**Comment by renhongkai** [comment]
将thumt的路径export下就可以了。

**Comment by KelleyYin** [comment]
谢谢，刚刚解决了。
