### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by KelleyYin** [thumt/THUMT#25]
![bug](https://user-images.githubusercontent.com/30852232/38672779-cd6abd60-3e81-11e8-8fe7-9cfba938b797.png)

I try to run Thumt-theano for testing my dataset. However, it arised a error . Does  anybody solve it ?
Thanks in advance .

**Comment by KelleyYin** [comment]
My commad is as follow .
`python /data2/hfyu/THUMT-theano/scripts/trainer.py --config-file  /data2/hfyu/THUMT-theano/config/THUMT.config --trn-src-file /data2/    hfyu/THUMT-theano/data/train.src --trn-trg-file /data2/hfyu/THUMT-theano/data/train.trg --vld-src-file /data2/hfyu/THUMT-theano/data/    valid.src --vld-trg-file /data2/hfyu/THUMT-theano/data/valid.trg --training-criterion 1 --init-model-file model_mle_best.npz --device     gpu1$
`

**Comment by Glaceon31** [comment]
It happens when --init-model-file is set and model_mle_best.npz does not exist. Do you have a pre-trained model for initialization? Set --init-model-file to that model if so. Or delete "--init-model-file model_mle_best.npz" if no pre-trained model exists.

**Comment by KelleyYin** [comment]
@Glaceon31 Thanks for your reply . "--init-model-file " have been deleted from my commad, but there have the erroy in my system .  This system requires cuda version 7.5 in official manual, however my cuda version is 8.0. Do you think the error could be caused by the discrepance ?

**Comment by Glaceon31** [comment]
The system can run with cuda 8.0. I'm sorry the previous answer is not right. It seems that the process to initialize with existing model is trigger by MRT and semi training (which is --criterion 1 or --criterion 2) and it loops and causes error if the model for initialization is not found. Using --criterion 0 for MLE training will get rid of the error. If you want to train with MRT, we recommend to train with MLE first and initialize MRT with the best model output by MLE using "--init-model-file ". We will add some tips in order not to confuse the users :-)
