### ISSUE TITLE
About train_steps

### ISSUE THREAD

**Issue by renhongkai** [thumt/THUMT#26]
How to determine the end of the training? The parameter train_steps in train.py is 100000, but the program is still executing after 100000.Thank you very much.

**Comment by KelleyYin** [comment]
Do you know the cause of the issue ?  #27 

My program is seem to not stop in the iteration limit and how to solve it ?

Thanks in advance !

**Comment by renhongkai** [comment]
Hi,you can stop the tranining by changing the parameter 'train_steps'.

At 2018-04-14 16:25:40, "KelleyYin" <notifications@github.com> wrote:


Do you know the cause of the issue ? #27

My program is seem to not stop in the iteration limit and how to solve it ?

Thanks in advance !
