### ISSUE TITLE
The error of decoding

### ISSUE THREAD

**Issue by Julisa-test** [thumt/THUMT#31]
`(venv-2.7.14) ubuntu@ubuntu:~/python2.7/tensorflow$ sed -r ’s/(@@ )|(@@ ?$)//g’ < newstest2015.trans > newstest2015.trans.norm
bash: syntax error near unexpected token `('
`
How can i solve this problem？ 
Thanks！

**Comment by Playinf** [comment]
The command should be `sed -r 's/(@@ )|(@@ ?$)//g'`.
