### ISSUE TITLE
Implementation Question: why scaling the embeddings by square root of hidden size?

### ISSUE THREAD

**Issue by Epsilon-Lee** [thumt/THUMT#42]
Do this influence the final performance? I haven't see it in Google's implementation. Many thanks! 
```    
if params.multiply_embedding_mode == "sqrt_depth":
        inputs = inputs * (hidden_size ** 0.5)
```

**Comment by Glaceon31** [comment]
Hi, Google's implementation includes this in _modalities.py_

**Comment by Epsilon-Lee** [comment]
Thanks for pointing out, I missed that detail! BTW, do you have any insights/intuitions on why scale the embeddings? Many thanks.

**Comment by Glaceon31** [comment]
I guess that maybe scaling is empirically better than no scaling. It is better to ask the Tensor2tensor developers for an accurate explanation.

**Comment by Epsilon-Lee** [comment]
Thanks a lot, I will do that.
