### ISSUE TITLE
has the latest version added MultiGPU training module?

### ISSUE THREAD

**Issue by alphadl** [thumt/THUMT#50]
That's an important and efficient training trick to speed the training, I saw your teams' paper before which said that would implement multiGPU function soon , however , I can not find any description in your readme file~

**Comment by Glaceon31** [comment]
Yes, the `device_list` parameter allows MultiGPU training

> device_list: the list of GPUs to be used in training. Use the nvidia-smi command to nd unused GPUs. If the unused GPUs are gpu0 and gpu1, set this parameter as device_list=[0,1].

Please refer to `UserManual.pdf` for detailed usage.

**Comment by alphadl** [comment]
okay, many thanks
