### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by xudekuan** [thumt/THUMT#6]
我们用tesla k80 单个gpu进行测试，代码为
sudo python trainer.py --config-file config/THUMT.config --trn-src-file data/train.src --trn-trg-file data/train.trg --vld-src-file data/valid.src  --vld-trg-file data/valid.trg --device gpu0 --replace-unk

程序能运行，但是，用nividia-smi检测，发现gpu没有启用，

**Comment by xudekuan** [comment]
请问，可能是什么原因呢？

**Comment by xudekuan** [comment]
![tim 20170921134058](https://user-images.githubusercontent.com/30224318/30680657-85d63a68-9ed3-11e7-9ee8-5eb013b7f837.png)

**Comment by xudekuan** [comment]
![tim 20170921134853](https://user-images.githubusercontent.com/30224318/30680688-a400be00-9ed3-11e7-9c0c-5dd9404d2e10.png)
程序正在运行中

**Comment by xudekuan** [comment]
已经解决。
安装了 cudnn v5（以前安装的是 v6），现在这个报错已经没有了

并且

gpu 有使用率了。

**Comment by Glaceon31** [comment]
感谢测试！应该是当前版本的Theano和cudnn v6不兼容。
