### ISSUE TITLE
Monolingual data never used??

### ISSUE THREAD

**Issue by Jmallins** [thumt/THUMT#9]
I dont think the monolingual data is ever used. It is loaded into the array self.target_mono (data.py) but never read from again. 

I checked this by printing out xm, ym = data.next_mono() (train.py) and found none of my monolingual data was ever within it.

Additionally (im not sure it matters) but I believe if self.config['sort_batches'] is even it will never enter the  (next_mono, data.py)if not self.inited or self.batch_id == self.config['sort_batches'] within  (thus never adding monolingual data), if it is odd it will never enter (next, data.py) if not self.inited or self.batch_id == self.config['sort_batches'], never adding bilingual data.

**Comment by Glaceon31** [comment]
Hi, are you doing semi-supervised training (which means config['semi_learning'] is True)? The monolingual data is only used in semi-supervised training.

**Comment by Jmallins** [comment]
Yes, Im doing semi supervised

**Comment by Glaceon31** [comment]
Sorry for the late. I find a typo in the code which may cause the error. It is fixed now.

**Comment by Jmallins** [comment]
Yes, I found that error and fixed it. But i still think monolingual data is never used. please feel free to print out the content of  xm, ym = data.next_mono() and i think you should see no monolingual data in there. By monolingual data I mean data that is not in the bilingual dataset.

**Comment by Glaceon31** [comment]
This is weird, I print xm,ym and there is data in them. Can you provide your log and your command?

**Comment by Jmallins** [comment]
yes there is data, but it wont be the monolingual data. it just contains bilingual data

**Comment by Glaceon31** [comment]
Oh there is a huge bug in loading data. Sorry for the inconvenience. Please inform me if the newest version does not fix the bug!
